"""Phonotactic statistics over the Khazalid / Zharralid source words.

Reads  references/raw/source_words.tsv   (from tools/extract_source_words.py)
Writes spec/phonology_analysis.md        human-readable report
       src/klazan/data/source_stats.json aggregated counts only (no word list),
                                          used by klazan.wordgen as its
                                          "sounds dwarvish" model

    uv run python tools/analyze_phonology.py
"""

from __future__ import annotations

import csv
import json
from collections import Counter
from pathlib import Path

from klazan.phonology import has_geminate, segment, shape

ROOT = Path(__file__).resolve().parents[1]
WORDS = ROOT / "references" / "raw" / "source_words.tsv"
REPORT = ROOT / "spec" / "phonology_analysis.md"
STATS = ROOT / "src" / "klazan" / "data" / "source_stats.json"

SOURCES = ("khazalid", "zharralid")


def load() -> dict[str, list[str]]:
    by_src: dict[str, list[str]] = {s: [] for s in SOURCES}
    with WORDS.open(encoding="utf-8") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            if row["kind"] == "native" and row["tag"] != "name":
                by_src[row["source"]].append(row["word"])
    return {s: sorted(set(ws)) for s, ws in by_src.items()}


def stats(words: list[str]) -> dict:
    c = {k: Counter() for k in ("initial", "final", "medial", "nucleus",
                                 "final_nucleus", "consonant", "syllables",
                                 "ending2", "ending3", "trigram")}
    gem = 0
    for w in words:
        sh = shape(w)
        c["initial"][sh.initial] += 1
        c["final"][sh.final] += 1
        c["syllables"][sh.syllables] += 1
        for m in sh.medials:
            c["medial"][m] += 1
        for n in sh.nuclei:
            c["nucleus"][n] += 1
        if sh.nuclei:
            # nucleus of the last syllable, tagged open/closed
            c["final_nucleus"][sh.nuclei[-1] + ("#" if not sh.final else "C")] += 1
        segs = segment(w)
        for s in segs:
            if s not in "aeiouy":
                c["consonant"][s] += 1
        c["ending2"][w[-2:]] += 1
        c["ending3"][w[-3:]] += 1
        padded = ["<", "<"] + segs + [">"]
        for i in range(2, len(padded)):
            c["trigram"][" ".join(padded[i - 2:i + 1])] += 1
        gem += has_geminate(w)
    return {"n": len(words), "geminate": gem, **c}


def pct(n: int, total: int) -> str:
    return f"{100 * n / total:.1f}%" if total else "-"


def table(title: str, per_src: dict[str, Counter], totals: dict[str, int],
          top: int = 25, label=lambda k: k or "∅") -> str:
    combined = sum(per_src.values(), Counter())
    keys = [k for k, _ in combined.most_common(top)]
    lines = [f"### {title}", "", "| | " + " | ".join(SOURCES) + " | combined |",
             "|---|" + "---:|" * (len(SOURCES) + 1)]
    tot_all = sum(totals.values())
    for k in keys:
        cells = [pct(per_src[s][k], totals[s]) for s in SOURCES]
        lines.append(f"| `{label(k)}` | " + " | ".join(cells)
                     + f" | {pct(combined[k], tot_all)} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    words = load()
    st = {s: stats(ws) for s, ws in words.items()}
    n = {s: st[s]["n"] for s in SOURCES}

    def tot(key: str) -> dict[str, int]:
        return {s: sum(st[s][key].values()) for s in SOURCES}

    out = ["# Phonology analysis of the source languages", "",
           "Generated by `tools/analyze_phonology.py` from the *native* words of the "
           "fan lexicons (calques like *victraz*, English words, AI-invented entries "
           "and god/place names excluded). Clusters are written with `.` between "
           "segments (`th.r` = th + r). `∅` = empty cluster. Percentages are "
           "within each column.", "",
           "| | " + " | ".join(SOURCES) + " |", "|---|---:|---:|",
           "| words | " + " | ".join(str(n[s]) for s in SOURCES) + " |",
           "| mean syllables | " + " | ".join(
               f"{sum(k * v for k, v in st[s]['syllables'].items()) / n[s]:.2f}"
               for s in SOURCES) + " |",
           "| vowel-initial | " + " | ".join(
               pct(st[s]["initial"][""], n[s]) for s in SOURCES) + " |",
           "| vowel-final | " + " | ".join(
               pct(st[s]["final"][""], n[s]) for s in SOURCES) + " |",
           "| has geminate (zz, rr…) | " + " | ".join(
               pct(st[s]["geminate"], n[s]) for s in SOURCES) + " |", ""]
    out.append(table("Syllables per word", {s: st[s]["syllables"] for s in SOURCES},
                     n, top=6, label=str))
    out.append(table("Word-initial clusters", {s: st[s]["initial"] for s in SOURCES},
                     n, top=35))
    out.append(table("Word-final clusters", {s: st[s]["final"] for s in SOURCES},
                     n, top=30))
    out.append(table("Medial clusters (between vowels)",
                     {s: st[s]["medial"] for s in SOURCES}, tot("medial"), top=35))
    out.append(table("Vowel nuclei (all syllables)",
                     {s: st[s]["nucleus"] for s in SOURCES}, tot("nucleus"), top=15))
    out.append(table("Last-syllable vowel (`#` = word ends in it, `C` = closed)",
                     {s: st[s]["final_nucleus"] for s in SOURCES}, n, top=12))
    out.append(table("Consonant segments", {s: st[s]["consonant"] for s in SOURCES},
                     tot("consonant"), top=30))
    out.append(table("Word endings (last 2 letters)",
                     {s: st[s]["ending2"] for s in SOURCES}, n, top=25))
    out.append(table("Word endings (last 3 letters)",
                     {s: st[s]["ending3"] for s in SOURCES}, n, top=20))
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(out), encoding="utf-8")

    STATS.parent.mkdir(parents=True, exist_ok=True)
    keep = ("initial", "final", "medial", "nucleus", "syllables", "trigram")
    STATS.write_text(json.dumps(
        {s: {"n": n[s], **{k: dict(st[s][k].most_common()) for k in keep}}
         for s in SOURCES}, indent=1, sort_keys=True), encoding="utf-8")
    print(f"wrote {REPORT.relative_to(ROOT)} and {STATS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
